name: slot_attention6
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - ld_impl_linux-64=2.40
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.45.3
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.1
  - pip=24.0
  - python=3.12.3
  - readline=8.2
  - setuptools=70.0.0
  - tk=8.6.13
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - certifi==2024.6.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - executing==2.0.1
      - fastcluster==1.2.6
      - fastjsonschema==2.19.1
      - filelock==3.14.0
      - fonttools==4.53.0
      - fqdn==1.5.1
      - fsspec==2024.6.0
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h11==0.14.0
      - html2image==2.0.5
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.23.3
      - hydra-core==1.3.2
      - hypnettorch==0.0.4
      - idna==3.7
      - imageio==2.34.2
      - ipykernel==6.29.4
      - ipython==8.25.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - kagglehub==0.3.3
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - lxml==5.2.2
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - mpmath==1.3.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - notebook==7.2.0
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.40
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - omegaconf-argparse==1.0.1
      - opencv-python==4.10.0.84
      - overrides==7.7.0
      - packaging==24.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathlib==1.0.1
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.2.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.46
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.1.2
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - referencing==0.35.1
      - regex==2024.5.15
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.1
      - safetensors==0.4.3
      - scikit-image==0.25.0
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.4.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - sparsemax==0.1.9
      - stack-data==0.6.3
      - sympy==1.12.1
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2024.12.12
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - torch==2.3.1
      - torchvision==0.18.1
      - tornado==6.4
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.41.2
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.1
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==2.2.1
      - wandb==0.17.0
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.11